name: Pack LeviLamina&LegacyScriptEngine
on:
  workflow_dispatch:
    inputs:
      LeviLamina:
        description: 'LeviLamina version'
        required: true
        default: '1.1.0'
      LSE:
        description: 'LegacyScriptEngine version'
        required: true
        default: '0.10.0'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    permissions:
      contents: write
    runs-on: windows-latest
    steps: 
    - name: Download Lip
      run: |
        Invoke-WebRequest -Uri https://github.com/futrime/lip/releases/download/v0.28.3/lip-cli-win-x64.zip -OutFile ./lip.zip
        Expand-Archive -Path .\lip.zip -DestinationPath .\
        del lip.zip
        mkdir LeviLamina

    - name: Download LeviLamina & Delete BDS
      working-directory: LeviLamina
      run: |
        ..\lip.exe install github.com/LiteLDev/LeviLamina@${{ github.event.inputs.LeviLamina }}
        copy .\tooth_lock.json .\tooth_lock.json.bak
        ..\lip.exe uninstall github.com/LiteLDev/bds
        del .\tooth_lock.json
        Rename-Item .\tooth_lock.json.bak tooth_lock.json
        del allowlist.json
        del bedrock_server_mod.exe
        del permissions.json
        del server.properties
        del -Path .\.cache -Recurse
    - name: Download LSE & Get BDS Version
      working-directory: LeviLamina
      id: get_bds_core_version
      run: |
        ..\lip install github.com/LiteLDev/LegacyScriptEngine#lua@${{ github.event.inputs.LSE }}
        ..\lip install github.com/LiteLDev/LegacyScriptEngine#quickjs@${{ github.event.inputs.LSE }}
        ..\lip install github.com/LiteLDev/LegacyScriptEngine#nodejs@${{ github.event.inputs.LSE }}
        ..\lip install github.com/LiteLDev/LegacyScriptEngine#python@${{ github.event.inputs.LSE }}
        $res = Get-content  -Raw -Path ".\tooth_lock.json" |ConvertFrom-Json
        "bds_core_version=$($res.packages[1].manifest.version)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
    - name: Pack files
      working-directory: LeviLamina
      run: |
        Compress-Archive -Path * -DestinationPath "LeviLamina-${{ github.event.inputs.LeviLamina }} with LSE-${{ github.event.inputs.LSE }}.zip"
        copy "LeviLamina-${{ github.event.inputs.LeviLamina }} with LSE-${{ github.event.inputs.LSE }}.zip" ..\
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: "LeviLamina-${{ github.event.inputs.LeviLamina }} with LSE-${{ github.event.inputs.LSE }}.zip" 
        name: LeviLamina-${{ github.event.inputs.LeviLamina }}&LSE-${{ github.event.inputs.LSE }}
        tag_name: ${{ github.event.inputs.LeviLamina }}&${{ github.event.inputs.LSE }}
        body: |
          LeviLamina版本: ${{ github.event.inputs.LeviLamina }}
          LSE版本: ${{ github.event.inputs.LSE }}
          适用的BDS版本(仅供参考): ${{ steps.get_bds_core_version.outputs.bds_core_version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
